version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: keylocker_user
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: keylocker_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DB_USER: keylocker_user
      DB_PASSWORD: yourpassword
      DB_NAME: keylocker_db
      DB_HOST: db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  pgdata:
