"""Add temp_token and sessions_token to users

Revision ID: 060384003cfe
Revises: ffc46333d77d
Create Date: 2025-10-17 21:39:46.346729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060384003cfe'
down_revision = 'ffc46333d77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('temp_token_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('session_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('session_token_expires_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_token_expires_at')
        batch_op.drop_column('session_token')
        batch_op.drop_column('temp_token_expires_at')
        batch_op.drop_column('temp_token')

    # ### end Alembic commands ###
