"""Add site column to VaultItem

Revision ID: 25c3253a2dd5
Revises: 060384003cfe
Create Date: 2025-10-18 19:08:36.574193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c3253a2dd5'
down_revision = '060384003cfe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_items', schema=None) as batch_op:
        batch_op.drop_column('site')

    # ### end Alembic commands ###
